[package]
name = "wav_convolution"
version = "0.1.0"
edition = "2021"

# No reason to distribute a VST plugin on crates.io.
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "^ 3.4"
